### ISSUE TITLE
Can i set size for side panes?

### ISSUE THREAD

**Issue by gf59ru** [cmv/cmv-app#350]
Cmv-app has panes described in ```viewer.js```:
```panes: {
	left: {
		splitter: true
	},
	bottom: {
		id: 'sidebarBottom',
		placeAt: 'outer',
		splitter: true,
		collapsible: false,
		region: 'bottom'
	},
	top: {
		id: 'sidebarTop',
		placeAt: 'outer',
		collapsible: false,
		splitter: false,
		region: 'top'
	}
}```
May i set initial size (width for left and right panes or height for top and bottom)?
And set size for them in further?

**Comment by tmcgee** [comment]
You can set the initial size of a pane in three ways (at least):

* change the width or height property for the corresponding sidebar class in `main.css`.

``` css
#sidebarLeft {
    display: block;
    width: 200px;
    padding: 4px;
    margin: 0px;
    overflow: auto;
    overflow-x: hidden;
    background-color: transparent;
}
```

* override the width or height property for the corresponding sidebar class in your own css file like `app.css`. I prefer this option over the previous option because I have one main.css used by multiple apps.

``` css
#sidebarLeft {
    width: 200px;
}
```

* add in-line styling to the pane in the panes option in `viewer.js`.
``` javascript
panes: {
    left: {
        splitter: true,
        style: 'width: 200px;'
    }
},
```

NOTE that `main.css` has some media queries at the bottom of the file that override the widths for devices with smaller screens so you'll need to account for those too. Because of this, I prefer to set the size using css in a stylesheet file, not in-line styling for the pane.

You can change the sizing through code by adding/removing/toggling css classes (using dojo's dom-class) or by updating the size in the style attributes (using dojo's dom-style).
