### ISSUE TITLE
Geocode widget doesn't work inside a titlePane

### ISSUE THREAD

**Issue by roemhildtg** [cmv/cmv-app#559]
If you try to put the Geocode widget inside a titlepane it has some display issues that don't work quite right. 

![image](https://cloud.githubusercontent.com/assets/5471079/15682568/f1086992-2723-11e6-97a6-d0d42dbc082b.png)

The config to produce the issue looks like this: 
```javascript
      geocoder: {
        include: true,
        title: 'Address Search',
        id: 'geocoder',
        type: 'titlePane',
        position: 0,
        // type: 'domNode',
        path: 'gis/dijit/Geocoder',
        // srcNodeRef: 'geocodeDijit',
        options: {
          map: true,
          mapRightClickMenu: true,
          geocoderOptions: {
            autoComplete: true,
            arcgisGeocoder: {
              placeholder: 'Enter an address or place'
            }
          }
        }
      },
```

I haven't really tested this much but something like this might work:

```css
.gis_GeocoderDijit .esriGeocoder {
    height: 28px;
}

.gis_GeocoderDijit .searchContainer {
    /* position: absolute; */
    /* top: 0; */
    /* left: 100%; */
    width: 175px;
    height: 30px;
    margin-left: 30px;
}

.gis_GeocoderDijit .open .zoomSearchButton {
    float: left;
    height: 30px;
}
```
