### ISSUE TITLE
Bug: Sublayer Menu doesn't appear for dynamic layers with only one layer

### ISSUE THREAD

**Issue by roemhildtg** [cmv/cmv-app#603]
![image](https://cloud.githubusercontent.com/assets/5471079/18800446/9b26c508-81a2-11e6-8930-bef258127bab.png)

It turns out dynamic layers are built differently when they only have one layer...some logic needs to be added to add sublayer menus to dynamic layers with only one sublayer. 

P.S. you can assign me, I'll make a pull request to fix sometime in the next week I hope

**Comment by AESMM** [comment]
Hi, thanks for the fix.  Is there any way for this to function like the sub layer menus?  They appear as blue hyperlinked items with the sub menu appearing when clicked.  This would make the "Open Attribute Table" function more consistent with the sub layer options.  Or is it possible to add the menu "hamburger" button appear for sub-layers with menu items - this would make the entire UI consistent.

Thanks.

**Comment by roemhildtg** [comment]
That is true, they are somewhat inconsistent currently. I think the first option would be best since having lots of hamburgers (one for each layer) might clutter the ui up.

**Comment by AESMM** [comment]
Hi, any luck with the change to this yet?  Thanks.

**Comment by tmcgee** [comment]
@AESMM @roemhildtg Is this just a stylistic change that can be handled through CSS?

**Comment by roemhildtg** [comment]
No, the sublayer menu is set up on the sublayer's name, while the main layer's menu is set up underneath its 'hamburger'. I haven't had time to look into switching it yet. 

Quick thought, having menus in two different places is a bit confusing for the end user. Should we consider moving the "hamburger" menu to the layer name menu?

**Comment by tmcgee** [comment]
Depending on the individual requirements, you can setup a hamburger menu icon using css in your application. Not suggesting you should have separate icons/colors for each menu (bad UX IMHO), but you could do that if you really wanted too...

![image](https://cloud.githubusercontent.com/assets/200780/19835409/e85337dc-9e42-11e6-9cae-a2308025226a.png)


```css
.layerControlDijit .menuLink {
    color: inherit;
}

.layerControlDijit .menuLink:hover {
    color: inherit;
    text-decoration: underline;
    cursor: pointer;
}

.layerControlDijit .menuLink:first-child:after {
    color: #00B;
    content:  '\f0c9';
    font-family: FontAwesome;
    margin-left:  10px;
}

.layerControlDijit #louisvillePubSafety-2-sublayer-control .menuLink:first-child:after {
    color:  #B00;
    content:  '\f05a';
}

.layerControlDijit #louisvillePubSafety-4-sublayer-control .menuLink:first-child:after {
    color:  #000;
    content:  '\f19d';
}

.layerControlDijit #louisvillePubSafety-5-sublayer-control .menuLink:first-child:after {
    color:  #00B;
    content:  '\f0fd';
}

.layerControlDijit #louisvillePubSafety-8-sublayer-control .menuLink:first-child:after {
    color:  #666;
    content:  '\f03d';
}
```

note that I had to use `first-child` in the css selector because there are 2 span tags. the second one is empty and does trigger the menu.
